### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Kamalamalar** [sameerkumar18/pyaztro#14]
>>> import pyaztro
>>> horoscope = pyaztro.Aztro(sign='aries')
Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    horoscope = pyaztro.Aztro(sign='aries')
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\site-packages\pyaztro\aztro.py", line 44, in __init__
    'Could not get a successful response from aztro API', r.content)
pyaztro.exceptions.PyAztroInvalidAPIResponseException: Could not get a successful response from aztro API
>>>

**Comment by Madbrad200** [comment]
The source the API used is dead.

https://github.com/sameerkumar18/pyaztro/issues/13

https://github.com/sameerkumar18/aztro/issues/42#issuecomment-1493276688

> Gee that's interesting, it's going to be hard for Sameer to fix as this code has been scraping my website for years without me knowing and I've been paying $$$ to AWS for database and hosting fees. Unfortunately, I am not going to be bringing the website back as a free resource to be scraped anymore.
